using './main.bicep'

param location = 'swedencentral'
param logAnalyticsWorkspaceId = '/subscriptions/edccd614-120e-4738-9be5-e63d2c6b7b10/resourceGroups/ghdemo/providers/Microsoft.OperationalInsights/workspaces/lawghdemo'
param appServicePlanId = '/subscriptions/edccd614-120e-4738-9be5-e63d2c6b7b10/resourceGroups/ghdemo/providers/Microsoft.Web/serverfarms/spghdemo'
param webAppName = 'githubdemo-web'
param sqlServerName = 'githubdemo-sql'
param databaseName = 'Movies'
param databaseSku = 'Basic'
param sqlAdminGroupName = 'GitHub Demo Movie Database Admins'
param sqlAdminGroupId = 'c7886e28-f000-4a50-ae0b-1df4e3504037'
param stagingDatabaseSku = 'Basic'
