using './main.bicep'

param location = 'swedencentral'
param logAnalyticsWorkspaceName = 'ondfisk-githubdemo-logs'
param appServicePlanName = 'ondfisk-githubdemo-plan'
param webAppName = 'ondfisk-githubdemo-web'
param sqlServerName = 'ondfisk-githubdemo-sql'
param databaseName = 'Movies'
param databaseSku = 'Basic'
param sqlAdminGroupName = 'GitHub Demo Movie Database Admins'
param sqlAdminGroupId = '93cb57ad-624e-428a-99f0-b12d49e7dc2a'
param stagingDatabaseSku = 'Basic'
