---
name: Lint

"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions: {}

jobs:
  build:
    name: Lint
    runs-on: ubuntu-latest

    permissions:
      contents: write
      statuses: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Super-Linter
        uses: super-linter/super-linter@v7.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_JSCPD: false
          VALIDATE_GIT_COMMITLINT: false
          FIX_JSON: true
          FIX_JSON_PRETTIER: true
          FIX_JSONC: true
          FIX_JSONC_PRETTIER: true
          FIX_MARKDOWN: true
          FIX_MARKDOWN_PRETTIER: true
          FIX_YAML_PRETTIER: true
      - name: Commit and push linting fixes
        if: github.event_name == 'pull_request' && github.ref_name != github.event.repository.default_branch
        uses: stefanzweifel/git-auto-commit-action@v6.0.1
        with:
          branch: ${{ github.event.pull_request.head.ref || github.head_ref || github.ref }}
          commit_message: "chore: fix linting issues"
          commit_user_name: super-linter
          commit_user_email: super-linter@super-linter.dev
